### ISSUE TITLE
Logo for Blitzbot

### ISSUE THREAD

**Issue by linadesteem** [CodeMan99/blitzbot#10]
Hi

I designed a logo for your bot. What do you think? I can upload svg file if you like it

![blitzbot](https://user-images.githubusercontent.com/35618068/39092012-a84a8490-462c-11e8-9ffc-46c62c810e76.png)

**Comment by linadesteem** [comment]
i can change it to other color if you like it

**Comment by CodeMan99** [comment]
Nice work.

However, any logo needs to work as an avatar for discord as that's where most interaction happens.

My current logo.
![blitzbot logo](https://cdn.discordapp.com/icons/174749939920797697/a21424e3e88b727a899a929b857ee46a.webp)

This logo is mostly functional, it also has a nice border that fits within the Discord user interface since most of the time when you see the logo it is in a circle. That said, the file is a square and the area outside the border _is_ used.

Unselected guild logo.
<img width="59" alt="screen shot 2018-04-22 at 4 52 38 pm" src="https://user-images.githubusercontent.com/6373201/39099771-aa25a1ac-464d-11e8-85df-6e68228c558a.png">

Selected guild logo.
<img width="57" alt="screen shot 2018-04-22 at 4 48 38 pm" src="https://user-images.githubusercontent.com/6373201/39099717-0c49f2b2-464d-11e8-9ebb-ebe286fdf7c6.png">

Bot in the user list.
<img width="150" alt="screen shot 2018-04-22 at 4 53 47 pm" src="https://user-images.githubusercontent.com/6373201/39099776-c62b5ff4-464d-11e8-80c1-5bfb552c29c1.png">

The message (cozy UI, compact UI has no avatar).
<img width="747" alt="screen shot 2018-04-22 at 4 55 09 pm" src="https://user-images.githubusercontent.com/6373201/39099793-008c33bc-464e-11e8-8e18-322130d7dad7.png">

**Comment by CodeMan99** [comment]
Acceptable image sizes.

 * 512x512
 * 768x768
 * 1024x1024

**Comment by anilkilic** [comment]
Here is an alternative which can work in circular areas.
![all](https://user-images.githubusercontent.com/2311397/39663985-f084d050-5084-11e8-9b85-b311a1ea9d94.png)
![ss](https://user-images.githubusercontent.com/2311397/39663987-f2503262-5084-11e8-8a67-5598b8131743.png)
![side](https://user-images.githubusercontent.com/2311397/39663994-0a8e9e72-5085-11e8-9704-0dc7847a4d2c.png)

Here are the files 1024px, 768px, 512px and svg for further edits. Hope you like it.
[Google Drive](https://drive.google.com/open?id=1YZwBGaAJ7nRUGEshIrRv4w6w4xa-deGC)

**Comment by CodeMan99** [comment]
Requested access to the google drive files with codemister99@gmail.com.

**Comment by anilkilic** [comment]
Sorry about that, I've re-checked the sharing permission, the same link should work without an access right. 
https://drive.google.com/open?id=1YZwBGaAJ7nRUGEshIrRv4w6w4xa-deGC

**Comment by CodeMan99** [comment]
So I think I like the simple hood the most (right most of all.svg).

* Do the hood a light blue like #20bdf5. Bring down the high points a little, like 10%?
* Do the lightning yellow like #71ff00.
* Do the eye color like #dbcfcf.
* The mouth should be less wide (15% ?). Color it to complement the hood (but not the same). At the moment I have #005371.
* The primary "skin" color should be a gradient to make it appear like a light source is between 1:00 and 2:00. Might want the hood to be a gradient too, but I'm not sure.
* Remove the eye plate completely. I think it complicates the design too much.

**Comment by anilkilic** [comment]
I put a folder named *rev01* into Google Drive, same link.
![hoodrev](https://user-images.githubusercontent.com/2311397/39665457-488716e2-509d-11e8-846d-7acf916d64b7.png)

- I didn't quite understand what you mean by
> The primary "skin" color should be a gradient to make it appear like a light source is between 1:00 and 2:00. Might want the hood to be a gradient too, but I'm not sure.

[Google Images:Light Source](https://www.google.com/search?q=light+source&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjEyr2Dg-_aAhXJY8AKHS6iALIQ_AUICigB&biw=1508&bih=911)

**Comment by CodeMan99** [comment]
I meant the angle of the gradient. If you look at a clock face, I want the brightest part of the gradient to be between 1:00 & 2:00. The darkest part of the gradient at 7:00 or 8:00 of the clock face.

As for the light source, think a little 3d. There is your view (the camera), the target (the logo), and light source somewhere in space. It would be cool to make the gradient appear that there is a light source as described above.

**Comment by anilkilic** [comment]
![rev02](https://user-images.githubusercontent.com/2311397/39668050-209801e4-50cc-11e8-935d-35147df83d52.png)
?

**Comment by CodeMan99** [comment]
Nice! Bottom right with the black background looks great to me.

**Comment by CodeMan99** [comment]
Do you think you could get these resulting files added into revision history? Thinking in a new sub-directory called "logo".

**Comment by CodeMan99** [comment]
#11 merged.
