### ISSUE TITLE
Is down on discord

### ISSUE THREAD

**Issue by Paralied** [CodeMan99/blitzbot#32]
Bot is down on discord

**Comment by CodeMan99** [comment]
Back up. FYI, this project is currently on life support. There is very little motivation for me to do the large amount of work to upgrade the [discord dependency](https://github.com/CodeMan99/blitzbot/blob/bdf146c977bf545fb2fa2a642db76cc9a22e5e55/package.json#L31). Which is the first step to making _blitzbot_ more stable.

This is mostly because I no longer play the game. The average player count is way down and seems to be in a sinking trend. If I'm reading the room wrong, please let me know!

**Comment by Paralied** [comment]
The player base fluctuates but your bot is used quite a bit by pro players

**Comment by CodeMan99** [comment]
Could you define "pro" please? Do you just mean "really good"? Or do you mean something like "they play the game on stream" or "they play the game competitively in eSports" ?

**Comment by Paralied** [comment]
Really good players, could range from decent to etournaments level
